version: '3.3'

services:
  leantime_db:
    image: mysql:8.4
    container_name: leantime-mysql
    volumes:
      - ./db_data:/var/lib/mysql
    restart: unless-stopped
    env_file: ./.env                                        # Environment file with settings
    networks:
      - leantime-net
    command: --character-set-server=UTF8MB4 --collation-server=UTF8MB4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
  mcp:
    container_name: leantime-mcp
    build:
      context: ./fastmcp-python          # path to the directory containing your Dockerfile
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - leantime-net
  leantime:
    image: leantime/leantime:3.7.3 # ${LEAN_VERSION:-latest}
    container_name: leantime
    restart: unless-stopped
    env_file: ./.env                                        # Environment file with settings
    # Add security options
    security_opt:
      - no-new-privileges:true
    # Add capabilities
    cap_add:
      # - CAP_NET_BIND_SERVICE
      - CAP_CHOWN
      - CAP_SETGID
      - CAP_SETUID
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"

      # WEB (everything except /api)
      - "traefik.http.routers.leantime.rule=Host(`leantime.app.apecia.local`)"
      - "traefik.http.routers.leantime.entrypoints=websecure"
      - "traefik.http.routers.leantime.tls=true"
      - "traefik.http.services.leantime.loadbalancer.server.port=8080"
      # HTTP → HTTPS Redirect
      - "traefik.http.routers.leantime-http.rule=Host(`leantime.app.apecia.local`)"
      - "traefik.http.routers.leantime-http.entrypoints=web"
      - "traefik.http.routers.leantime-http.middlewares=leantime-redirect"

      # Redirect Middleware
      - "traefik.http.middlewares.leantime-redirect.redirectscheme.scheme=https"

    networks:
      - leantime-net
      - traefik-public
    volumes:
      - public_userfiles:/var/www/html/public/userfiles     # Volume to store public files, logo etc
      - userfiles:/var/www/html/userfiles                   # Original volume name for compatibility
      - plugins:/var/www/html/app/Plugins                   # Plugin storage
      - logs:/var/www/html/storage/logs                     # Log storage
    depends_on:
      leantime_db:
        condition: service_healthy

  # Add a helper container for volume permissions
  # Run via docker compose --profile mysql_helper up -d
  mysql_helper:
    image: mysql:8.4
    container_name: leantime-mysql-helper
    command: chown -R mysql:mysql /var/lib/mysql
    volumes:
      - db_data:/var/lib/mysql
    user: root
    profiles: [ "helper" ]

volumes:
  userfiles:                                               # New volume for public files
  public_userfiles:
  plugins:
  logs:

networks:
  leantime-net:
  traefik-public:
    external: true
